"use strict";
let car1 = 'Saburu';
let car2 = 'Mustang';
let car3 = 'Saburu';
console.log("Test 1: is car1 == 'Saburu'? I predict True!");
console.log(car1 == 'Saburu');
console.log("Test 2: is car2 == 'Mustang'? I predict True!");
console.log(car2 == 'Mustang');
console.log("Test 3: is car1 == 'Mustang'? I predict False!");
console.log(car1 == 'Mustang');
console.log("Test 4: is car2 == 'Saburu'? I predict False!");
console.log(car2 == 'Saburu');
console.log("Test 5: is car1 == 'Mustang'? I predict False!");
console.log(car1 != 'Mustang');
console.log("Test 6: is car2 == 'Saburu'? I predict False!");
console.log(car2 != 'Saburu');
console.log("Test 7: is car1 == 'NULL'? I predict False!");
console.log(car1 == 'NULL');
console.log("Test 8: is car2 == 'NULL'? I predict False!");
console.log(car2 == 'NULL');
console.log("Test 9: is 'Saburu' == 'Saburu'? I predict False!");
console.log(car1 == car3);
console.log("Test 10: is 'Saburu' == 'Saburu'? I predict False!");
console.log(car2 == car3);
